"""
Database models for storing research agent results in Postgres.

Stores research reports with title, summary, findings, and sources.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any

from sqlalchemy import DateTime, String, Text, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from sqlalchemy.types import JSON


class Base(DeclarativeBase):
    """SQLAlchemy declarative base."""


def _json_type() -> type[JSON]:
    """
    Use a portable JSON column type.

    Postgres will store this as JSON; if you want JSONB specifically later, we can
    introduce dialect-specific types via migrations.
    """
    return JSON


class ResearchReport(Base):
    """
    Research report generated by the agent_research agent.

    Stores the complete research report including title, executive summary,
    key findings, and formatted sources.
    """

    __tablename__ = "research_reports"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)

    # Research metadata
    research_topic: Mapped[str] = mapped_column(String(512), nullable=False, index=True)

    # Report content
    title: Mapped[str] = mapped_column(String(512), nullable=False)
    executive_summary: Mapped[str] = mapped_column(Text, nullable=False)
    key_findings: Mapped[list[str]] = mapped_column(_json_type(), nullable=False)  # type: ignore[arg-type]
    sources: Mapped[str] = mapped_column(
        Text, nullable=True
    )  # Formatted sources string

    # Full report JSON for flexibility
    report_data: Mapped[dict[str, Any] | None] = mapped_column(
        _json_type(), nullable=True
    )  # Full report JSON

    # Research configuration
    research_loop_count: Mapped[int] = mapped_column(nullable=False, default=1)

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False, index=True
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
